---
label: Post
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: cover
  label: Cover
  type: file
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: ''
- name: author
  label: Author
  type: text
  hidden: false
  default: ''
pages:
- _posts/news/2018-11-15-game-day.md
- _posts/classes/2018-11-01-toastmasters.md
